checkov:
    stage: build
    script: echo "Just copy results"
    artifacts:
        paths:
            - checkov_results.xml
        reports:
            junit: checkov_results.xml

include:
  - template: Security/SAST.gitlab-ci.yml