# The following CI file can be used as an example for how to call
# Probe as part of a GitLab CI pipeline.

stages:
- test

run probe:
  image:
    name: registry.gitlab.aws.dev/tsd/probe/standalone-scanner:latest
    entrypoint: [""]
  stage: test
  script:
    # https://gitlab.com/gitlab-org/gitlab-runner/-/merge_requests/3538 - mark directory as safe
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - /usr/bin/python3 -u /exec/app.py
  artifacts:
    paths:
    - ${CI_PROJECT_DIR}/probe-out/*
    reports:
      junit: ${CI_PROJECT_DIR}/probe-out/probe_report.xml
