version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.13
      nodejs: 22
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - npm install aws-cdk-lib aws-cdk -g
      - npm install
      - CDK_STACK=$(aws cloudformation list-stacks --query 'StackSummaries[?(StackName==`CDKToolkit` && StackStatus==`CREATE_COMPLETE`)].StackId' --output text)
  build:
    commands:
      - if [ -z "$CDK_STACK" ] ; then cdk bootstrap ; else echo "Already bootstrapped" ; fi
      - export CLOUDHSM_EXPRESS=false
      - chmod +x ./scripts/get_azs.sh
      - chmod +x ./scripts/deploy.sh
      - ./scripts/deploy.sh
artifacts:
  files: 'out.json'
